### ISSUE TITLE
Feature: As a user, I want aiSSEMBLE 1.8.0 released, so I have access to the latest features. (Preparation)

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#199]
## Description
We are ready to cut the release for 1.8.0. We are still in process of getting GitHub actions ready for the release so will continue to use the old infrastructure for this release.

## DOD
Acceptance criteria required to realize the requested feature
Before release:
- [x] Apply the bug patch to fix the environment variable substitutions issues
   - [x] also check and fix other Dockerfile if it has the same issues
- [x] Fix issues blocking release
  - [x] Fabric8 Dockerfile substitution creating broken images (#201)
  - [x] Remove snapshot dependencies (#204)
  - [x] Setup mirror for Fabric8 (#208 - _TODO: Create post_)
  - [x] Fix PDP bugs from rename effort (#218)
  - [x] Apply best practices to Pipeline Invocation chart (#220)
  - [x] Shrink/stream-line Quarkus images (#225, #237)
  - [x] Flatten/stream-line FastAPI images (#225)
  - [x] Remove inadvertent Vault container creation outside of ITs (#239 )

Follow-on: #238

## Test Strategy/Script
1. Validate that the latest CI build has completed successfully
2. Run the policy decision point image: `docker run --pull=always --rm -p8080:8080 ghcr.io/boozallen/aissemble-policy-decision-point:1.8.0-SNAPSHOT`
3. Verify the service is running: `curl localhost:8080/api/healthcheck`
4. Submit an auth request and verify `NOT_APPLICABLE` is returned
```
curl -X POST -H "Content-Type: application/json" localhost:8080/api/pdp -d '{
  "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI3ZDZmMWZlNS05YzZiLTQ1ZGEtODlmMS0yMDM5YWIwNWZhNDEiLCJzdWIiOiJhaW9wcyIsImF1ZCI6ImF1ZGllbmNlIiwibmJmIjoxNjI0OTc2MDI5LCJpYXQiOjE2MjQ5NzYwMjksImV4cCI6MTkyNDk4MDc5NywiaXNzIjoiYWlvcHMuYXV0aG9yaXR5In0.eUBC2ink77XRf5n5JIXlLZR-fBiRmGrqo1TBFz46yZhWDY38dsh30flELE8gO5SG2rUSIe-VmmjSny8PFLNGwy5MGLwr9z56HoH7OrejJeEzCa1yBl67VWgUZhoDy3RzvARfdBnUstfigHYeQA2ECvW-b2kppYJPVUNX2uKmwfZupwqCGqIX56s7qntV0dUAjpC_KiZ3fjUz1HXqK_evWos0xPVT8XOB2ZADhh87kf7LmocYQ4Y-Z_fsou6jqYh1lQT8WeI2AKskE613nSqmTA2bax5-dOFXKWKLy8t5glyjkdqFZVrLrNkK9tXqNYpZ8efIkZKOu7T9TlsvkHU1XQ",
  "resource": "data-access",
  "action": "get"
}'
```
5. Run encryption build without ITs: `mvn clean install -pl :aissemble-extensions-encryption-vault-python`
6. Verify Vault is not started during the build (see build output)

## References/Additional Context
Refer to this document for release process:
https://github.com/boozallen/aissemble/blob/release-action/.github/workflows/RELEASE.md

**Comment by csun-cpointe** [comment]
DoD completed with @nartieri @carter-cundiff and @Cho-William

**Comment by ewilkins-csi** [comment]
OTS with @carter-cundiff

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/user-attachments/assets/74459fe9-3141-436d-90b1-37d52cc2c58b)
![image](https://github.com/user-attachments/assets/ae22ec91-033d-4bb4-bf1a-474a4c620b24)
