### ISSUE TITLE
As an aiSSEMBLE team member, I want all issues to have consistent content and formatting to encourage clear and concise communication and tracking.

### ISSUE THREAD

**Issue by nartieri** [boozallen/aissemble#91]
## Description
To better align the github issues that are created for the aiSSEMBLE project with the aiSSEMBLE team's standard operating procedures, we want a way to consistently structure and include appropriate content across issues. By applying a github issue template we should be able to include the appropriate fields to be completed, align the titles of those fields to team norms for more cohesive tracking, and provide examples of the content to be included for each issue type. The DOD below may shift based on some initial investigation regarding the ability to tailor templated based on the aiSSEMBLE team's regular ticket types of Features, Bugs, and Tasks.

## DOD
- [x] An Issue Template for Enhancements will exist
- [x] An Issue Template for Bugs will exist
- [x] An Issue Template for Tasks will exist

## Additional context
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

## Test strategy/script
1. Select the New Issue button
2. Select the Get Started button for each issue type
3. Verify that the template is applied to the issue, the correct fields and field names are included, and the starter content is included to prompt issue creators.

**Comment by nartieri** [comment]
Provided initial cut at Feature/Enhancement Issue template for internal review. Will update the subsequent Issue types with a similar format after feedback and/or initial testing of the template.

**Comment by nartieri** [comment]
I have applied similar templates and logic to the Bug and Task issue templates. I will create a branch and propose the changes via PR.

**Comment by nartieri** [comment]
OTS'd with Emily. PR approved by Ryan. PR merged and ticket is ready for test.

**Comment by nartieri** [comment]
Testing completed and successful. Will look into vulnerability reporting process updates next.
